# Generated by Django 4.1.1 on 2022-10-29 11:19

from django.db import migrations, models
import medapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('sure_name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('hospital_number', models.CharField(max_length=30)),
                ('hospital_name', models.CharField(max_length=50)),
                ('hospital_phone', models.CharField(max_length=10)),
                ('relative_firstname', models.CharField(max_length=30)),
                ('relative_surename', models.CharField(max_length=30)),
                ('relative_relation', models.CharField(max_length=30)),
                ('relative_phone', models.CharField(max_length=10)),
                ('disease', models.JSONField()),
                ('physical', models.JSONField()),
                ('memory', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to=medapp.models.user_directory_path)),
                ('face', models.JSONField()),
            ],
        ),
    ]
