# Generated by Django 4.1.1 on 2022-10-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elder',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='elder',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
