# Generated by Django 4.1.1 on 2022-10-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0002_elder_description_elder_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elder',
            name='description',
        ),
    ]
