# Generated by Django 4.1.1 on 2022-10-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0004_alter_elder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elder',
            name='image',
            field=models.ImageField(upload_to='images/<django.db.models.fields.CharField>'),
        ),
    ]
