# Generated by Django 4.1.1 on 2022-10-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0005_alter_elder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elder',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
